version: '3.7'
services:
  postgres:
    image: postgres:16
    container_name: social-network
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
   
